name: deploy-model-training-pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: deploy-model-training-pipeline-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-config:
    uses: Azure/mlops-templates/.github/workflows/read-yaml.yml@main
    with:
      file_name: config-infra-prod.yml

  create-compute:
    needs: get-config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Create Compute
        run: |
          az ml compute create --name test-cluster \
            --size Standard_DS11_v2 \
            --min-instances 0 \
            --max-instances 1 \
            --type amlcompute \
            --tier dedicated \
            --resource-group ${{ needs.get-config.outputs.resource_group }} \
            --workspace-name ${{ needs.get-config.outputs.aml_workspace }}

  register-dataset:
    needs: get-config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Register Dataset
        run: |
          az ml data create --file mlops/azureml/train/data.yml \
            --resource-group ${{ needs.get-config.outputs.resource_group }} \
            --workspace-name ${{ needs.get-config.outputs.aml_workspace }}

  register-environment:
    needs: get-config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Register Environment
        run: |
          az ml environment create --file mlops/azureml/train/train-env.yml \
            --resource-group ${{ needs.get-config.outputs.resource_group }} \
            --workspace-name ${{ needs.get-config.outputs.aml_workspace }}

  run-pipeline:
    needs: [get-config, register-environment, create-compute, register-dataset]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Run Pipeline
        run: |
          az ml job create --file mlops/azureml/train/newpipeline.yml \
            --resource-group ${{ needs.get-config.outputs.resource_group }} \
            --workspace-name ${{ needs.get-config.outputs.aml_workspace }} \
            --name mlops-pipeline
